### ISSUE TITLE
Failing to build with ament in isolation

### ISSUE THREAD

**Issue by clalancette** [stonier/ecl_core#69]
I have an Ubuntu 16.04 container with `ecl_tools`, `ecl_lite`, `ecl_core`, and `sophus` checked out in a workspace.  If I try to build in isolation:

```
ament build --isolated --make-flags VERBOSE=1
```

Then the build fails with:

```
[ 16%] Building CXX object src/lib/CMakeFiles/ecl_exceptions.dir/standard_exception.cpp.o
cd /home/ubuntu/ecl_ws/build_isolated/ecl_exceptions/src/lib && /usr/bin/c++   -DROS_PACKAGE_NAME=\"ecl_exceptions\" -Decl_exceptions_EXPORTS -isystem /home/ubuntu/ecl_ws/install_isolated/ecl_config/include  -std=c++14 -Wall -Wextra -Wl,--no-as-needed -fPIC   -o CMakeFiles/ecl_exceptions.dir/standard_exception.cpp.o -c /home/ubuntu/ecl_ws/src/ecl_core/ecl_exceptions/src/lib/standard_exception.cpp
In file included from /home/ubuntu/ecl_ws/src/ecl_core/ecl_exceptions/src/lib/standard_exception.cpp:19:0:
/home/ubuntu/ecl_ws/src/ecl_core/ecl_exceptions/src/lib/../../include/ecl/exceptions/standard_exception.hpp:31:35: fatal error: ecl/errors/handlers.hpp: No such file or directory
compilation terminated.
```

It looks like ecl_exception isn't properly pulling in the include directories for ecl_error, but I'm not quite sure how to fix it.

**Comment by stonier** [comment]
Switched over my build to use the isolated flag. Naively I assumed ament was doing isolated by default. Error reproduced. Will fix it as I can between meetings today.

**Comment by stonier** [comment]
* [x] [ecl_lite/pull_request/17](https://github.com/stonier/ecl_lite/pull/17)
* [x] [ecl_core/pull_request/70](https://github.com/stonier/ecl_core/pull/70)

**Comment by clalancette** [comment]
Just tested it locally, and isolated builds work now.  Thanks!
